defaults:
  - _self_
  - algorithm: dqn
  - environment: cc_cartpole
  - search_space: arlbench_dqn
  - override hydra/sweeper: HyperPB2

load: false
save: false
reward_curves: false

hydra:
  sweeper:
    budget: ${multiply:${environment.n_total_timesteps},${hydra.sweeper.sweeper_kwargs.optimizer_kwargs.population_size}}
    budget_variable: autorl.n_total_timesteps
    loading_variable: load
    saving_variable: save
    search_space: ${search_space}
    sweeper_kwargs:
      optimizer_kwargs:
        population_size: 16
        config_interval: ${divide:${environment.n_total_timesteps},10}
        seed: ${pbt_seed}
      checkpoint_tf: true
      load_tf: true
      checkpoint_path_typing: ""
      maximize: true
      max_parallelization: 1
  run:
    dir: ./results/arlbench/${algorithm}_${autorl.env_name}_pb2/config_interval_${hydra.sweeper.sweeper_kwargs.optimizer_kwargs.config_interval}/
  sweep:
    dir: ./results/arlbench/${algorithm}_${autorl.env_name}_pb2/config_interval_${hydra.sweeper.sweeper_kwargs.optimizer_kwargs.config_interval}/
  job:
    chdir: true

pbt_seed: 0
jax_enable_x64: false

algorithm_framework: arlbench
n_total_timesteps: ${environment.n_total_timesteps}
n_eval_steps: 1
n_eval_episodes: 128
seed: 42

autorl:
  seed: ${seed}
  env_framework: ${environment.framework}
  env_name: ${environment.name}
  env_kwargs: ${environment.kwargs}
  eval_env_kwargs: ${environment.eval_kwargs}
  n_envs: ${environment.n_envs}
  algorithm: ${algorithm}
  cnn_policy: ${environment.cnn_policy}
  nas_config: ${nas_config}
  n_total_timesteps: ${environment.n_total_timesteps}
  checkpoint: []
  checkpoint_name: "default_checkpoint"
  checkpoint_dir: "/tmp"
  state_features: []
  objectives: ["reward_mean"]
  optimize_objectives: "upper"
  n_steps: 10
  n_eval_steps: 1
  n_eval_episodes: 128