defaults:
  - _self_
  - search_space: hpo_rl_bench_ppo
  - override hydra/sweeper: HyperSMAC

algorithm: PPO
env: Pong-v0
metric_key: "eval_avg_returns"
seed: 0
budget: 50
hp_config: 
  lr: -6
  gamma: 0.8
  clip: 0.2

hydra:
  sweeper:
    n_trials: 30
    sweeper_kwargs:
      optimizer_kwargs:
        smac_facade: 
          _target_: smac.facade.blackbox_facade.BlackBoxFacade
          _partial_: true
        scenario:
          n_trials: ${hydra.sweeper.n_trials}
          seed: ${search_space.seed}
          deterministic: true
          n_workers: 1
          output_directory: ${hydra.sweep.dir}
    search_space: ${search_space}
  run:
    dir: ./results/hpo_rl_bench/${algorithm}_${env}_smac/seed_${seed}
  sweep:
    dir: ./results/hpo_rl_bench/${algorithm}_${env}_smac/seed_${seed}